package paifillonaiefamiliaservidor;
import javax.swing.JOptionPane;
/**
 *
 * @author noemi
 */
public class DatosConexionForm extends javax.swing.JFrame {
    /**
     * Creates new form DatosConexionForm
     */
    private Porto porto;
    public Porto getPorto(){
        return porto;
    }
    public void setPorto(Porto porto){
        this.porto=porto;
    }
    public DatosConexionForm() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblPortoConexion = new javax.swing.JLabel();
        jTxtPortoConexion = new javax.swing.JTextField();
        jBtnConectar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLblPortoConexion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLblPortoConexion.setText("Porto de escoita:");

        jTxtPortoConexion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTxtPortoConexion.setText("5555");

        jBtnConectar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtnConectar.setText("Escoitar");
        jBtnConectar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnConectarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jLblPortoConexion, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtPortoConexion, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jBtnConectar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtPortoConexion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblPortoConexion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jBtnConectar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnConectarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnConectarMouseClicked
        //System.out.println("evt:"+evt);
        if (getPortoConexion()!=-1){
            porto.setPorto(getPortoConexion());
        }
        //System.out.println("porto:"+getPortoConexion());
    }//GEN-LAST:event_jBtnConectarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatosConexionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatosConexionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatosConexionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatosConexionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatosConexionForm().setVisible(true);
            }
        });
    }
    private void informarErro(String str){
         System.out.println("O número de porto debe ser superior a 1024");
         jTxtPortoConexion.setText("0");
         JOptionPane.showMessageDialog(this, str);
    }
    public int getPortoConexion(){
        int numPorto;
        String strErro;
        try{
            numPorto=Integer.parseInt(jTxtPortoConexion.getText());
            if ((numPorto>0)&&(numPorto<1024)){
                strErro="O número de porto debe ser superior a 1024";
                numPorto=-1;
                informarErro(strErro);
            }
        }catch(Exception e){
            numPorto=-1;
            strErro="Formato de porto incorrecto. Debe ser un enteiro";
            informarErro(strErro);
        }
        return numPorto;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnConectar;
    private javax.swing.JLabel jLblPortoConexion;
    private javax.swing.JTextField jTxtPortoConexion;
    // End of variables declaration//GEN-END:variables
}
