package paifillonaiefamiliacliente;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.border.EtchedBorder;
/**
 *
 * @author noemi
 */
public class DatosConexionClienteForm extends javax.swing.JFrame {
    private final Color cores[]={Color.RED, Color.BLUE, Color.GREEN,Color.YELLOW};
    private DatosConexionCliente datosConexionCliente;
    public DatosConexionCliente getDatosConexionCliente(){
        return datosConexionCliente;
    }
    public void setDatosConexionCliente(DatosConexionCliente datosConexionCliente){
        this.datosConexionCliente=datosConexionCliente;
    }
    private void inicializarCombo(){
        DefaultComboBoxModel<Color> modelo=new DefaultComboBoxModel<Color>();
        
        for (Color cor:cores){
            modelo.addElement(cor);
        }
        this.jCmbCorCliente.setModel(modelo);
        this.jCmbCorCliente.setSelectedIndex(0);
        this.jCmbCorCliente.setRenderer(new CorRenderer());
        this.jCmbCorCliente.setOpaque(true);
        
        for (int i = 0; i < this.jCmbCorCliente.getComponentCount(); i++) {
            if (this.jCmbCorCliente.getComponent(i) instanceof JComponent) { 
                    ((JComponent) this.jCmbCorCliente.getComponent(i)).setBorder(BorderFactory.createEtchedBorder(EtchedBorder.LOWERED));
                }
        }        
    }
    public DatosConexionClienteForm() {
        initComponents();
        inicializarCombo();
        datosConexionCliente=new DatosConexionCliente();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblNomeServidor = new javax.swing.JLabel();
        jTxtNomeServidor = new javax.swing.JTextField();
        jBtnConectar = new javax.swing.JButton();
        jLblPortoConexion = new javax.swing.JLabel();
        jTxtPortoConexion = new javax.swing.JTextField();
        jLblNickCliente = new javax.swing.JLabel();
        jTxtNickCliente = new javax.swing.JTextField();
        jLblCorCliente = new javax.swing.JLabel();
        jCmbCorCliente = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLblNomeServidor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLblNomeServidor.setText("Nome do servidor:");

        jTxtNomeServidor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTxtNomeServidor.setText("PC-NOEMI");

        jBtnConectar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtnConectar.setText("Conectar");
        jBtnConectar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnConectarMouseClicked(evt);
            }
        });

        jLblPortoConexion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLblPortoConexion.setText("Porto do servidor:");

        jTxtPortoConexion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTxtPortoConexion.setText("5555");

        jLblNickCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLblNickCliente.setText("Nick do cliente:");

        jTxtNickCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLblCorCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLblCorCliente.setText("Cor do cliente:");

        jCmbCorCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCmbCorCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbCorClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jBtnConectar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLblCorCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCmbCorCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLblNickCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtNickCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLblPortoConexion, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTxtPortoConexion, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLblNomeServidor, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTxtNomeServidor, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtNomeServidor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblNomeServidor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtPortoConexion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblPortoConexion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtNickCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblNickCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCmbCorCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLblCorCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jBtnConectar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnConectarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnConectarMouseClicked
        if (getPortoConexion()!=-1){
            String nome=getNomeServidor();
            String nick=getNickCliente();
            Color cor=getCorCliente();
            String erro="";
            if ((!nome.equals(""))&& (!nick.equals(""))){
                datosConexionCliente.setPorto(getPortoConexion());
                datosConexionCliente.setNomeServidor(nome);
                datosConexionCliente.setNickCliente(nick);
                datosConexionCliente.setCorCliente(cor);
                datosConexionCliente.changeData(this);
            }else{
                if (nome.equals("")){
                    erro="Debes indicar o nome do servidor\n";
                }
                if (nick.equals("")){
                    erro+="Debes indicar un nick para o xogo\n";
                }
                JOptionPane.showMessageDialog(this, erro);
            }
        }
    }//GEN-LAST:event_jBtnConectarMouseClicked

    private void jCmbCorClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbCorClienteActionPerformed
        Color corGris=this.jCmbCorCliente.getComponent(0).getBackground();
        Color corSel=(Color)this.jCmbCorCliente.getSelectedItem();
        this.jCmbCorCliente.setBackground(corSel);
        this.jCmbCorCliente.getComponent(0).setBackground(corGris);
    }//GEN-LAST:event_jCmbCorClienteActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatosConexionClienteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatosConexionClienteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatosConexionClienteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatosConexionClienteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatosConexionClienteForm().setVisible(true);
            }
        });
    }
    private void informarErro(String str){
         System.out.println(str);
         jTxtPortoConexion.setText("0");
         JOptionPane.showMessageDialog(this, str);
    }
    public int getPortoConexion(){
        int numPorto;
        String strErro;
        try{
            numPorto=Integer.parseInt(jTxtPortoConexion.getText());
        }catch(Exception e){
            numPorto=-1;
            strErro="Formato de porto incorrecto. Debe ser un enteiro";
            informarErro(strErro);
        }
        return numPorto;
    }
    public String getNomeServidor(){
        String str;
        str=jTxtNomeServidor.getText();
        return str;
    }
    public String getNickCliente(){
        return jTxtNickCliente.getText();
    }
    public Color getCorCliente(){
        return jCmbCorCliente.getBackground();
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnConectar;
    private javax.swing.JComboBox<Color> jCmbCorCliente;
    private javax.swing.JLabel jLblCorCliente;
    private javax.swing.JLabel jLblNickCliente;
    private javax.swing.JLabel jLblNomeServidor;
    private javax.swing.JLabel jLblPortoConexion;
    private javax.swing.JTextField jTxtNickCliente;
    private javax.swing.JTextField jTxtNomeServidor;
    private javax.swing.JTextField jTxtPortoConexion;
    // End of variables declaration//GEN-END:variables
}
