package paifillonaiefamiliacliente;
import java.awt.Color;
import java.awt.FlowLayout;
import java.util.Observable;
import java.util.Observer;
/**
 *
 * @author noemi
 */
public class GUICliente extends javax.swing.JFrame  implements Observer{
    /**
     * Creates new form GUICli
     */
    public GUICliente() {
        //System.out.println("construtor GUICliente");
        initComponents();
        
    }
    private DatosXogo datosXogo;
    public void setDatosXogo(DatosXogo datosXogo){
        //System.out.println("entra en setDatosXogo");
        this.datosXogo=datosXogo;
    }
    public DatosXogo getDatosXogo(){
        return datosXogo;
    }
    public void setJLblMsgServidor(String msg){
        this.jLblMsgServidor.setText(msg);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLblNick = new javax.swing.JLabel();
        jLblNomeServidor = new javax.swing.JLabel();
        jLblPortoServidor = new javax.swing.JLabel();
        jLblCorTexto = new javax.swing.JLabel();
        jLblCor = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLblMsgServidor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLblNick.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLblNick.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLblNick.setText("Nick:");

        jLblNomeServidor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLblNomeServidor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLblNomeServidor.setText("Nome do servidor:");

        jLblPortoServidor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLblPortoServidor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLblPortoServidor.setText("Porto do servidor:");

        jLblCorTexto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLblCorTexto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLblCorTexto.setText("Cor:");

        jLblCor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLblCor.setText("  ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblNick)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLblCorTexto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLblCor, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblPortoServidor, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLblNomeServidor, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblNick)
                    .addComponent(jLblNomeServidor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLblCorTexto)
                        .addComponent(jLblCor))
                    .addComponent(jLblPortoServidor))
                .addGap(49, 49, 49))
        );

        jPanel2.setPreferredSize(new java.awt.Dimension(316, 316));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 316, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 323, Short.MAX_VALUE)
        );

        jLblMsgServidor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLblMsgServidor.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLblMsgServidor))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(jLblMsgServidor)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUICliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUICliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUICliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUICliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GUICliente cliente=new GUICliente();
                cliente.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLblCor;
    private javax.swing.JLabel jLblCorTexto;
    private javax.swing.JLabel jLblMsgServidor;
    private javax.swing.JLabel jLblNick;
    private javax.swing.JLabel jLblNomeServidor;
    private javax.swing.JLabel jLblPortoServidor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    public void setNickText(String jnickText){
        this.jLblNick.setText(jnickText);
    }
    public void setServerName(String serverName){
        this.jLblNomeServidor.setText(serverName);
    }
    public void setServerPort(String txt){
        this.jLblPortoServidor.setText(txt);
    }
    public void setCorCliente(Color cor){
        //System.out.println("Entra en setCorCliente con cor:"+cor.toString());
        this.jLblCor.setOpaque(true);
        this.jLblCor.setBackground(cor);
    }
    public void ponCuadricula(){
        GUICuadricula cuadricula=new GUICuadricula(10,10);
        cuadricula.setDatosXogo(datosXogo);
        cuadricula.engadirObservadores();
        jPanel2.setLayout(new FlowLayout());
        jPanel2.add(cuadricula);
        jPanel2.setVisible(true);
    }

    @Override
    public void update(Observable o, Object arg) {
        //System.out.println("entra en update de GuiCliente:"+o.toString());
        DatosXogo dx=(DatosXogo)o;
        if (DatosXogo.numXogadores==1)
            this.jLblMsgServidor.setText("Conectado co servidor. Esperando segundo xogador");
        if (DatosXogo.numXogadores>1){
            if (dx.getCorCliente()!=jLblCor.getBackground()){
                jLblCor.setBackground(dx.getCorCliente());
            }
            if (dx.getTurno()){
                this.jLblMsgServidor.setText("Tócache xogar\n");
            }else{
                 if ((dx.getGanhador()) && (dx.getCorGanhador().equals(dx.getCorCliente()))){
                    this.jLblMsgServidor.setText("Gañaches a partida");
                }else if ((dx.getGanhador() && (dx.getCorGanhador().equals(dx.getCorOutro())))){ 
                    this.jLblMsgServidor.setText("Perdeches a partida");
                }else 
                    this.jLblMsgServidor.setText("Non é o teu turno de xogo\n");
            }
        }
    }
}